spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/${POSTGRES_DB:db-desfio}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update
    generate-ddl: true