server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true
    context-path: "/"
spring:
  application:
    name: aplicacao

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  main:
    allow-bean-definition-overriding: true
  # datasource:
  #   url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:my-database}
  #   username: ${DB_USERNAME:username}
  #   password: ${DB_PASSWORD:password}
  #   initialization-mode: always
  #   connectionTestQuery: 'SELECT 1'

  # jpa:
  #   properties:
  #     hibernate:
  #       dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  #   hibernate:
  #     ddl-auto: update
  #   generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
