server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true
    context-path: "/"
spring:
  application:
    name: aplicacao
  profiles:
    active: ${PROFILE:dev}


  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  main:
    allow-bean-definition-overriding: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
